[package]
name = "achievement-viewer"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.33.3"
egui = "0.33.3"
egui_extras = "0.27"
icu = { version = "2.1", default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
notify = "6.1.1"
walkdir = "2.5.0"
image = "0.25.1"
directories-next = "2.0.0"
rfd = "0.14.0"
thiserror = "1.0.0"
num-bigint = "0.4"
zerofrom = "0.1.6"
zerofrom-derive = "0.1.6"
quote = "1.0"
syn = "1.0"
proc-macro2 = "1.0"
chrono = "0.4.31"
rust-ini = "0.21"
rand = "0.8.5"
